ApiMonitoringService/Models/ErrorViewModel.cs
namespace ApiMonitoringService.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ApiMonitoringService/Models/LogsModels.cs
namespace ApiMonitoringService.Models
{
    public class RequestLog
    {
        public int Id { get; set; }
        public string Method { get; set; }
        public string Endpoint { get; set; }
        public string IpAddress { get; set; }
        public DateTime RequestTime { get; set; }
        public string RequestPayload { get; set; }
    }

    public class ResponseLog
    {
        public int Id { get; set; }
        public int RequestLogId { get; set; }
        public int StatusCode { get; set; }
        public string ResponsePayload { get; set; }
        public DateTime ResponseTime { get; set; }
    }

    public class ApiEndpoint
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string EndpointUrl { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    }
}

ApiMonitoringService/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ApiMonitoringService.Models;

namespace ApiMonitoringService.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ApiMonitoringService/Controllers/LogsController.cs
using ApiMonitoringService.Contacts;
using ApiMonitoringService.Services;
using Microsoft.AspNetCore.Mvc;

namespace ApiMonitoringService.Controllers
{
    
    public class LogsController : Controller
    {
        private readonly IMonitoringRepository _repository;

        public LogsController(ILogger<HomeController> logger,IMonitoringRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }
        private readonly ILogger<HomeController> _logger;

     

        [HttpGet]
        public async Task<IActionResult> Requests()
        {
            var logs =  await _repository.GetRequestLogsAsync();

            return View(logs);
        }


        [HttpGet]
        public async Task<IActionResult> Responses()
        {
            var logs =  await _repository.GetResponseLogsAsync();

            return View(logs);
        }
    }
}

ApiMonitoringService/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ApiMonitoringService/Views/Logs/Requests.cshtml
@model IEnumerable<ApiMonitoringService.Models.RequestLog>

@{
    ViewData["Title"] = "Request Logs";
}
<h1>@ViewData["Title"]</h1>


<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Method</th>
            <th>Endpoint</th>
            <th>IP Address</th>
            <th>Request Time</th>
            <th>Request Payload</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var log in Model)
        {
            <tr>
                <td>@log.Id</td>
                <td>@log.Method</td>
                <td>@log.Endpoint</td>
                <td>@log.IpAddress</td>
                <td>@log.RequestTime.ToString("yyyy-MM-dd HH:mm:ss")</td>
                <td>@log.RequestPayload</td>
            </tr>
        }
    </tbody>
</table>

ApiMonitoringService/Views/Logs/Responses.cshtml
@model IEnumerable<ApiMonitoringService.Models.ResponseLog>

@{
    ViewData["Title"] = "Response Logs";
}
<h1>@ViewData["Title"]</h1>


<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Request Log Id</th>
            <th>Status Code</th>
            <th>Response Payload</th>
            <th>Response Time</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var log in Model)
        {
            <tr>
                <td>@log.Id</td>
                <td>@log.RequestLogId</td>
                <td>@log.StatusCode</td>
                <td>@log.ResponsePayload</td>
                <td>@log.ResponseTime.ToString("yyyy-MM-dd HH:mm:ss")</td>
            </tr>
        }
    </tbody>
</table>


ApiMonitoringService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApiMonitoringService</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ApiMonitoringService.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ApiMonitoringService</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Logs" asp-action="requests">Request Logs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Logs" asp-action="responses">Response Logs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ApiMonitoringService - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>